[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tracing = "0.1"
anyhow = "1"
clap = { version = "4.5.40", features = ["derive"] }
